CREATE DATABASE COLLEGE
USE COLLEGE
CREATE TABLE GRS
(
	ID INT IDENTITY PRIMARY KEY,
	GR NVARCHAR(6) NOT NULL
)
CREATE TABLE SUBJS
(
	ID INT IDENTITY PRIMARY KEY,
	SUBJ NVARCHAR(30) NOT NULL
)
CREATE TABLE TEACHERS
(
	ID INT IDENTITY PRIMARY KEY,
	TEACHER NVARCHAR(20) NOT NULL	
)
CREATE TABLE TEACH_TO_SUBJ
(
	ID INT IDENTITY PRIMARY KEY,	
	TEACHER INT NOT NULL REFERENCES TEACHERS(ID) ON DELETE CASCADE,
	SUBJ INT NOT NULL REFERENCES SUBJS(ID) ON DELETE CASCADE
)
CREATE TABLE MAIN
(
	ID INT IDENTITY PRIMARY KEY,
	GR INT NOT NULL REFERENCES GRS(ID) ON DELETE CASCADE,
	SUBJ INT NOT NULL REFERENCES SUBJS(ID) ON DELETE CASCADE,
	HOURS_IN_TERM INT NOT NULL
)